/**
 * Content loader — reads all .md files under the configured vault at
 * build time, runs the Obsidian-compatible frontmatter + transform
 * pipeline, and exposes typed Post records + indexes (by tag, by
 * slug, backlinks).
 *
 * The vault is a separate git repository, cloned into ./vault by
 * scripts/setup-vault.mjs (or `npm run vault:pull`). To swap the
 * vault, edit src/vault.config.ts and re-pull.
 *
 * Uses Vite's import.meta.glob with query=raw and eager=true to inline
 * every markdown file as a string. This is the simplest path for an
 * SPA without a backend; the cost is that the entire vault ships in
 * the JS bundle. Fine for personal blogs up to a few hundred posts.
 * For larger vaults, swap this for non-eager glob and lazy-load per route.
 */
import {
  parseFrontmatter,
  type PostFrontmatter,
  extractInlineTags,
  transformCallouts,
  findWikiLinks,
  slugify,
  isAttachmentPath,
  extractFirstImage,
} from './obsidian';
import { vaultPublicConfig } from '@/vault.public';
// vaultConfig is intentionally not imported here — the vault path is
// a build-time concern enforced by Vite's static glob below.

/**
 * Per-file creation timestamps extracted from the vault's git history.
 * Generated by `npm run vault:pull` and saved to `.vault-meta.json`
 * at the project root. content.ts reads it as a sidecar so we don't
 * have to shell out to git during the Vite build.
 *
 * Keyed by the vault-relative path the same way `import.meta.glob`
 * returns it (with a leading slash, e.g. "/中医/黄帝内经素问遗篇 1.md").
 */
import vaultMeta from '../../.vault-meta.json';

const creationTimes: Record<string, string> = (vaultMeta as { creationTimes?: Record<string, string> }).creationTimes ?? {};

export interface Post {
  /** URL slug derived from filename or frontmatter id */
  slug: string;
  /** Original filename relative to the vault root, e.g. "notes/hello.md" */
  sourcePath: string;
  /** Frontmatter */
  frontmatter: PostFrontmatter;
  /** Raw markdown body (after frontmatter strip) */
  raw: string;
  /** Markdown body with callouts transformed to fenced divs */
  body: string;
  /** Tags: union of frontmatter tags + inline #tags */
  tags: string[];
  /** Outgoing wiki-link targets, normalized to slugs */
  links: string[];
  /** Computed excerpt */
  excerpt: string;
  /** ISO date string */
  date: string;
  /** Title for display */
  title: string;
  /**
   * Resolved cover image URL. Priority:
   *   1. `cover` from frontmatter (absolute URL, /path, or attachment path)
   *   2. First image found in the body (Obsidian embed or markdown image)
   *   3. undefined — caller falls back to a deterministic gradient
   */
  cover?: string;
}

export interface Backlink {
  fromSlug: string;
  fromTitle: string;
  context: string;
}

export interface ContentIndex {
  posts: Post[];
  bySlug: Record<string, Post>;
  byTag: Record<string, Post[]>;
  backlinks: Record<string, Backlink[]>;
  tags: { name: string; count: number }[];
  /** Pillar (top-level dir) + Cluster (sub-dir) structure. */
  pillars: Pillar[];
  byCluster: Record<string, Cluster>; // clusterSlug -> Cluster
}

/**
 * A Pillar is a top-level directory in the vault. Each pillar can
 * contain clusters (sub-directories) and orphan posts (root .md
 * files inside the pillar). Mirrors the `pillar / cluster` SEO
 * model from blog-system.
 */
export interface Pillar {
  /** Slug used in URLs. Same as the directory name, slugified. */
  slug: string;
  /** Human-readable name, e.g. "中医" / "notes" / "projects" */
  name: string;
  /** One-line description (frontmatter or first post excerpt). */
  description: string;
  /** Optional cover image (from pillar.md, else first post). */
  cover?: string;
  /** Clusters under this pillar (sub-directories with .md). */
  clusters: Cluster[];
  /** Posts in this pillar that aren't inside any cluster. */
  posts: Post[];
  /** Total count (clusters.posts.length + posts.length). */
  postCount: number;
}

/**
 * A Cluster is a sub-directory under a pillar. Renders under the
 * pillar page as a sub-section.
 */
export interface Cluster {
  /** Slug of the form "<pillar>/<subdir>". */
  slug: string;
  /** The parent pillar's slug, for easy lookup. */
  pillarSlug: string;
  /** Human-readable name, e.g. "子文件夹". */
  name: string;
  description: string;
  cover?: string;
  posts: Post[];
}

// Vite-specific: this glob is replaced at build time. The pattern must
// be a string literal (Vite scans the source), so the vault root is
// hardcoded to match `vaultConfig.localPath`. If you change the path
// in src/vault.config.ts, update this glob too.
const modules = import.meta.glob<string>('/vault/**/*.md', {
  query: '?raw',
  import: 'default',
  eager: true,
});

function deriveTitle(fm: PostFrontmatter, sourcePath: string): string {
  if (typeof fm.title === 'string' && fm.title.trim()) return fm.title.trim();
  // filename without .md and without leading numeric date prefix (YYYY-MM-DD_)
  const base = sourcePath.split('/').pop() ?? sourcePath;
  const noExt = base.replace(/\.md$/i, '');
  const stripped = noExt.replace(/^\d{4}-\d{2}-\d{2}[-_ ]?/, '');
  return stripped.replace(/[-_]+/g, ' ').trim() || noExt;
}

function deriveDate(fm: PostFrontmatter, sourcePath: string): string {
  // gray-matter + js-yaml auto-parses YAML dates into Date objects.
  const rawDate = fm.date as unknown;
  if (rawDate instanceof Date && !Number.isNaN(rawDate.valueOf())) {
    return rawDate.toISOString();
  }
  if (typeof rawDate === 'string') {
    const d = new Date(rawDate);
    if (!Number.isNaN(d.valueOf())) return d.toISOString();
  }
  // try to extract a leading YYYY-MM-DD from filename
  const m = sourcePath.match(/(\d{4}-\d{2}-\d{2})/);
  if (m) {
    const d = new Date(m[1]);
    if (!Number.isNaN(d.valueOf())) return d.toISOString();
  }
  // 3rd fallback: the file's first-commit timestamp from the vault's
  // git history (extracted by `npm run vault:pull`, stored in
  // .vault-meta.json). The glob returns paths with a leading slash,
  // so normalize to match.
  const gitDate = creationTimes[sourcePath] || creationTimes[sourcePath.replace(/^\//, '')];
  if (gitDate) {
    const d = new Date(gitDate);
    if (!Number.isNaN(d.valueOf())) return d.toISOString();
  }
  return new Date(0).toISOString();
}

function makeExcerpt(body: string, max = 180): string {
  // strip headings, blockquotes, code fences, links
  const cleaned = body
    .replace(/```[\s\S]*?```/g, '')
    .replace(/^>.*$/gm, '')
    .replace(/^#+\s+.*$/gm, '')
    .replace(/\[\[([^\]]+)\]\]/g, (_, inner) => {
      const pipe = inner.indexOf('|');
      return pipe >= 0 ? inner.slice(pipe + 1) : inner;
    })
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, '')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/[*_`>#-]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  if (cleaned.length <= max) return cleaned;
  return cleaned.slice(0, max).replace(/\s+\S*$/, '') + '…';
}

function buildPost(sourcePath: string, raw: string): Post | null {
  const { data, content } = parseFrontmatter<PostFrontmatter>(raw);
  if (data.draft === true && import.meta.env.PROD) return null;

  const body = transformCallouts(content);
  const fmTags = Array.isArray(data.tags) ? data.tags.map(String) : [];
  const inlineTags = extractInlineTags(content);
  const tags = Array.from(new Set([...fmTags, ...inlineTags]));
  const links = findWikiLinks(content)
    .map((l) => l.slug)
    // Drop attachment targets (logos, PDFs, etc.) from the link graph.
    // They shouldn't show up as "outgoing wiki-links" for a post.
    .filter((slug) => !isAttachmentPath(slug));
  // Slug is the full vault-relative path (minus .md), so two files
  // with the same name in different folders stay distinct. The
  // matching slug for `[[dir/basename]]` references is produced by
  // remark-wikilink from the same path-based logic.
  const noExt = sourcePath.replace(/\.md$/i, '').replace(/^\/+/, '');
  const slug = slugify(noExt);
  return {
    slug,
    sourcePath,
    frontmatter: data,
    raw: content,
    body,
    tags,
    links,
    excerpt: makeExcerpt(content),
    date: deriveDate(data, sourcePath),
    title: deriveTitle(data, sourcePath),
    cover: resolveCover(data, content),
  };
}

/**
 * Resolve a Post's cover image. Priority:
 *   1. frontmatter `cover` (if string and non-empty)
 *   2. first image in the body — Obsidian embed or markdown image
 *
 * The result is always a URL that's safe to drop into an <img src>.
 * Attachment references get rewritten to /<publicAttachmentsPath>/...
 * so Vite's static handler can serve them.
 */
function resolveCover(fm: PostFrontmatter, content: string): string | undefined {
  const fmCover = typeof fm.cover === 'string' ? fm.cover.trim() : '';
  if (fmCover) return normalizeCoverUrl(fmCover);

  const first = extractFirstImage(content);
  if (!first) return undefined;
  return normalizeCoverUrl(first.target);
}

/**
 * Normalize a cover image target into a URL.
 *   - absolute http(s)  → kept as-is
 *   - starts with /     → kept as-is (already a public URL)
 *   - attachment path   → rewritten to /<publicAttachmentsPath>/<file>
 *   - anything else     → left to the browser (rare; usually a relative path)
 */
function normalizeCoverUrl(target: string): string {
  if (/^https?:\/\//i.test(target)) return target;
  if (target.startsWith('/')) return target;
  if (isAttachmentPath(target)) {
    const base = vaultPublicConfig.publicAttachmentsPath.replace(/\/+$/, '');
    const cleaned = target.replace(/^attachments\//, '');
    return `/${base}/${cleaned}`.replace(/\/+/g, '/');
  }
  return target;
}

function buildIndex(posts: Post[]): ContentIndex {
  const bySlug: Record<string, Post> = {};
  for (const p of posts) bySlug[p.slug] = p;

  const byTag: Record<string, Post[]> = {};
  for (const p of posts) {
    for (const t of p.tags) {
      (byTag[t] ??= []).push(p);
    }
  }

  const backlinks: Record<string, Backlink[]> = {};
  for (const p of posts) {
    for (const target of p.links) {
      const targetPost = bySlug[target];
      if (!targetPost) continue;
      (backlinks[target] ??= []).push({
        fromSlug: p.slug,
        fromTitle: p.title,
        context: p.excerpt,
      });
    }
  }

  const tags = Object.entries(byTag)
    .map(([name, list]) => ({ name, count: list.length }))
    .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));

  // Pillar / Cluster: derive from each post's sourcePath. The first
  // path segment is the pillar, the second (if any) is the cluster.
  // Posts at the vault root are NOT shown in the topic hierarchy
  // (they still appear in /blog). To give a pillar a description /
  // cover, drop a `pillar.md` or `_index.md` in that folder — its
  // frontmatter wins over the auto-derived values.
  const pillarMap = new Map<string, { name: string; posts: Post[]; clusterMap: Map<string, Post[]>; indexPost?: Post }>();
  for (const p of posts) {
    const parts = p.sourcePath.split('/').filter(Boolean);
    if (parts.length < 2) continue; // root-level file, skip
    const pillarName = parts[0]!;
    const clusterName = parts.length >= 3 ? parts[1]! : null;
    let pEntry = pillarMap.get(pillarName);
    if (!pEntry) {
      pEntry = { name: pillarName, posts: [], clusterMap: new Map() };
      pillarMap.set(pillarName, pEntry);
    }
    if (clusterName) {
      const arr = pEntry.clusterMap.get(clusterName) ?? [];
      arr.push(p);
      pEntry.clusterMap.set(clusterName, arr);
    } else {
      pEntry.posts.push(p);
    }
    // detect index file
    if (parts.length === 2 && /^(pillar|_index)\.md$/i.test(parts[1]!)) {
      pEntry.indexPost = p;
    }
  }

  const pillars: Pillar[] = [];
  for (const [pillarName, entry] of pillarMap) {
    // Sort posts in pillar: by date desc
    entry.posts.sort((a, b) => b.date.localeCompare(a.date));
    const clusters: Cluster[] = [];
    for (const [clusterName, cposts] of entry.clusterMap) {
      cposts.sort((a, b) => b.date.localeCompare(a.date));
      const indexCluster = cposts.find(
        (p) => /^(cluster|_index)\.md$/i.test(p.sourcePath.split('/').pop() ?? ''),
      );
      const c = indexCluster ?? cposts[0];
      clusters.push({
        slug: `${pillarName}/${clusterName}`,
        pillarSlug: pillarName,
        name: clusterName,
        description:
          (typeof c?.frontmatter.description === 'string' && c.frontmatter.description) ||
          c?.excerpt ||
          '',
        cover: c?.cover,
        posts: cposts,
      });
    }
    clusters.sort((a, b) => b.posts.length - a.posts.length || a.name.localeCompare(b.name));
    const indexPost = entry.indexPost ?? entry.posts[0] ?? clusters[0]?.posts[0];
    pillars.push({
      slug: pillarName,
      name: pillarName,
      description:
        (typeof indexPost?.frontmatter.description === 'string' && indexPost.frontmatter.description) ||
        indexPost?.excerpt ||
        '',
      cover: indexPost?.cover,
      clusters,
      posts: entry.posts,
      postCount: entry.posts.length + clusters.reduce((s, c) => s + c.posts.length, 0),
    });
  }
  pillars.sort((a, b) => b.postCount - a.postCount || a.name.localeCompare(b.name));

  const byCluster: Record<string, Cluster> = {};
  for (const c of pillars.flatMap((p) => p.clusters)) byCluster[c.slug] = c;

  return { posts, bySlug, byTag, backlinks, tags, pillars, byCluster };
}

let _index: ContentIndex | null = null;

function loadAll(): ContentIndex {
  if (_index) return _index;
  const posts: Post[] = [];
  for (const [path, raw] of Object.entries(modules)) {
    if (typeof raw !== 'string') continue;
    const post = buildPost(path.replace(/^\/vault\//, ''), raw);
    if (post) posts.push(post);
  }
  posts.sort((a, b) => b.date.localeCompare(a.date));
  _index = buildIndex(posts);
  return _index;
}

export function getAllPosts(): Post[] {
  return loadAll().posts;
}

export function getPostBySlug(slug: string): Post | undefined {
  return loadAll().bySlug[slug];
}

export function getPostsByTag(tag: string): Post[] {
  return loadAll().byTag[tag] ?? [];
}

export function getBacklinks(slug: string): Backlink[] {
  return loadAll().backlinks[slug] ?? [];
}

export function getAllTags(): { name: string; count: number }[] {
  return loadAll().tags;
}

export function getAllPillars(): Pillar[] {
  return loadAll().pillars;
}

export function getPillarBySlug(slug: string): Pillar | undefined {
  return loadAll().pillars.find((p) => p.slug === slug);
}

export function getClusterBySlug(slug: string): Cluster | undefined {
  return loadAll().byCluster[slug];
}

/**
 * Posts under a given pillar, including all its clusters' posts.
 * Sorted by date desc.
 */
export function getPostsByPillar(pillarSlug: string): Post[] {
  const pillar = getPillarBySlug(pillarSlug);
  if (!pillar) return [];
  return [...pillar.posts, ...pillar.clusters.flatMap((c) => c.posts)]
    .sort((a, b) => b.date.localeCompare(a.date));
}

export function getContentStats() {
  const idx = loadAll();
  return {
    posts: idx.posts.length,
    tags: idx.tags.length,
    links: idx.posts.reduce((acc, p) => acc + p.links.length, 0),
    pillars: idx.pillars.length,
  };
}
