/**
 * Google AdSense configuration types + helpers.
 *
 * The Ads kit is intentionally narrow — we ship:
 *  - the `google-adsense-account` verification meta tag
 *  - `ads.txt` generation (one entry per authorized seller)
 *  - the optional Auto Ads script (loaded once on every page)
 *
 * It does NOT ship ad-slot components or auto-injection of `<ins>` blocks —
 * those are page-template decisions, not framework concerns.
 *
 * @example
 *   // seo.config.ts
 *   import { defineAds } from 'seo-kit';
 *
 *   export const siteAds = defineAds({
 *     google: {
 *       publisherId: 'ca-pub-1234567890123456',
 *       // optional Auto Ads
 *       autoAds: true,
 *       // authorized sellers in ads.txt
 *       sellers: [
 *         {
 *           domain: 'google.com',
 *           publisherId: 'ca-pub-1234567890123456',
 *           relationship: 'DIRECT',
 *           certAuthorityId: 'f08c47fec0942fa0',
 *         },
 *       ],
 *     },
 *     // Cookie / GDPR consent gate (overrides Auto Ads until consent is given).
 *     consent: {
 *       required: true,
 *       policyUrl: '/privacy',
 *     },
 *   });
 *
 *   // Generate ads.txt at build time
 *   import { generateAdsTxt } from 'seo-kit';
 *   const txt = generateAdsTxt(siteAds);
 *   // -> "google.com, ca-pub-1234567890123456, DIRECT, f08c47fec0942fa0\n"
 */

import type { SiteAds } from './config-ads.ts';
export type { SiteAds, AdsSeller, GoogleAdsConfig, ConsentConfig } from './config-ads.ts';

// ─── Helpers ──────────────────────────────────────────────────────────

/** Identity helper for type-inference on the ads config object. */
export function defineAds<T extends SiteAds>(config: T): T {
  return config;
}

/** Returns true if the ads module is enabled (any provider configured). */
export function isAdsEnabled(config: SiteAds | undefined | null): boolean {
  if (!config) return false;
  return Boolean(config.google?.publisherId);
}

// ─── ads.txt generation ───────────────────────────────────────────────

/**
 * Build the full `ads.txt` file body. Always emits a comment header so
 * crawlers can tell the file is hand-curated.
 *
 * Output format per IAB spec:
 *   <domain>, <publisherId>, <relationship>, [certAuthorityId]
 *
 * If `config` is missing or empty, returns an empty string so callers can
 * `if (txt) writeFile(...)` and skip the file entirely.
 */
export function generateAdsTxt(config: SiteAds | undefined | null): string {
  if (!config || !config.google || !config.google.publisherId) return '';
  const sellers = config.google.sellers ?? [];

  const lines: string[] = [];
  lines.push('# ads.txt — Authorized Digital Sellers');
  lines.push('# Generated by seo-kit (see https://iabtechlab.com/ads-txt/)');
  lines.push(`# Last updated: ${new Date().toISOString().slice(0, 10)}`);

  for (const s of sellers) {
    const parts = [s.domain, s.publisherId, s.relationship];
    if (s.certAuthorityId) parts.push(s.certAuthorityId);
    if (s.subdomain) parts.push(`subdomain=${s.subdomain}`);
    lines.push(parts.join(', '));
  }
  return lines.join('\n') + '\n';
}

/**
 * Convenience: build a default ads.txt line for a single Google AdSense
 * seller. The CERT authority ID `f08c47fec0942fa0` is Google's official
 * TAG ID as published in their docs — it stays stable.
 */
export function googleAdsenseSeller(publisherId: string): {
  domain: string;
  publisherId: string;
  relationship: 'DIRECT' | 'RESELLER';
  certAuthorityId: string;
} {
  return {
    domain: 'google.com',
    publisherId,
    relationship: 'DIRECT',
    certAuthorityId: 'f08c47fec0942fa0',
  };
}

// ─── Auto Ads script snippet ──────────────────────────────────────────

/**
 * Returns the HTML <script> snippet that turns on Google Auto Ads.
 *
 * Per Google's docs, this script must be loaded on every page where ads
 * should appear. Setting `data-ad-frequency-hint` modulates density.
 *
 * The snippet is intentionally returned as a string (not injected
 * imperatively) so users can paste it into their template / SSR output.
 */
export function generateAutoAdsScript(
  config: SiteAds | undefined | null,
): string {
  if (!config?.google?.publisherId || !config.google.autoAds) return '';
  return (
    `<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${encodeURIComponent(config.google.publisherId)}" crossorigin="anonymous"></script>`
  );
}

// ─── Verification meta ────────────────────────────────────────────────

/**
 * Build the <meta name="google-adsense-account"> verification tag.
 *
 * Google prefers this over the `<script>` verification because it's
 * deterministic and doesn't require JS execution. We emit it on every page
 * regardless of Auto Ads state — verification is independent of ad loading.
 */
export function generateAdsenseVerificationMeta(
  config: SiteAds | undefined | null,
): string {
  if (!config?.google?.publisherId) return '';
  return `<meta name="google-adsense-account" content="${config.google.publisherId}" />`;
}