// ⚠ AUTO-GENERATED by scripts/build-config.mjs
//   Source: vault/_config.md (frontmatter + body yaml code blocks)
//   Do not edit this file directly — run `npm run build:config` after editing the vault config.

import type { SiteConfig } from './site-config.types';

export const siteConfig: SiteConfig = {
  "site": {
    "name": "笔记百科",
    "shortName": "笔记百科",
    "tagline": "融通东西方,笔记天下事",
    "description": "公众号笔记百科和这个东西的官方博客与工具箱，不断进化的文化内容与五明之学承载地，一站式精心打造的系统性个人成长与修身平台；本网站为纯静态部署，无服务器成本，有意向者请联系，微信号：rurufengxing。",
    "defaultTheme": "light",
    "themes": [
      "light",
      "dark",
      "sepia",
      "cyberpunk"
    ],
    "locale": "zh_CN",
    "defaultLanguage": "zh",
    "languages": [
      "zh",
      "en"
    ],
    "contentTheme": "default",
    "author": {
      "name": "笔记百科",
      "url": "https://bijibaike.com"
    },
    "social": {
      "github": "https://bijibaike.com",
      "twitter": "",
      "email": ""
    },
    "features": [
      {
        "text": "Bijibaike 出品",
        "icon": "Sparkles"
      }
    ]
  },
  "seo": {
    "siteUrl": "",
    "ogImage": "/og-image.svg",
    "keywords": [
      "文化",
      "儒释道",
      "栾巨庆",
      "天文地理",
      "知识管理",
      "个人成长",
      "工具"
    ],
    "twitter": ""
  },
  "ads": {
    "enabled": false,
    "publisherId": "",
    "verification": true,
    "autoAds": true,
    "consent": {
      "required": true,
      "categories": [
        "necessary",
        "marketing"
      ]
    }
  },
  "vault": {
    "repo": "Omlandc/bijibaike-article",
    "branch": "main",
    "ref": "",
    "publicAttachmentsPath": "/attachments"
  },
  "nav": [
    {
      "label": {
        "zh": "首页",
        "en": "Home"
      },
      "to": "/",
      "icon": "Home"
    },
    {
      "label": {
        "zh": "文章",
        "en": "Posts"
      },
      "to": "/blog",
      "icon": "FileText"
    },
    {
      "label": {
        "zh": "主题",
        "en": "Topics"
      },
      "to": "/topics",
      "icon": "FolderTree"
    },
    {
      "label": {
        "zh": "标签",
        "en": "Tags"
      },
      "to": "/tags",
      "icon": "Tag"
    },
    {
      "label": {
        "zh": "图谱",
        "en": "Graph"
      },
      "to": "/graph",
      "icon": "Network"
    },
    {
      "label": {
        "zh": "资源",
        "en": "Resources"
      },
      "to": "/resources",
      "icon": "BookOpen"
    },
    {
      "label": {
        "zh": "更新",
        "en": "Changelog"
      },
      "to": "/changelog",
      "icon": "History"
    }
  ],
  "footer": {
    "copyright": {
      "zh": "© 2026 笔记百科 · 本网站源码遵循源可用许可,商业使用需授权",
      "en": "© 2026 Bijibaike · Source-available, commercial use requires a license"
    },
    "links": [
      {
        "label": {
          "zh": "关于",
          "en": "About"
        },
        "to": "/about"
      },
      {
        "label": {
          "zh": "联系",
          "en": "Contact"
        },
        "to": "/contact"
      },
      {
        "label": {
          "zh": "授权定价",
          "en": "Pricing"
        },
        "to": "/pricing",
        "hidden": true
      },
      {
        "label": {
          "zh": "隐私",
          "en": "Privacy"
        },
        "to": "/privacy"
      }
    ],
    "showGithub": false
  },
  "pillars": [
    {
      "name": "中医",
      "description": "中医养生、经典与临床实践"
    },
    {
      "name": "其他",
      "description": "其他主题笔记"
    }
  ],
  "resources": {
    "sections": [
      {
        "title": "工具",
        "description": "需要的工具",
        "items": [
          {
            "title": "笔记百科cn",
            "url": "https://bijibaike.cn",
            "description": "笔记百科的备份地址，请收藏"
          }
        ]
      },
      {
        "title": "文献",
        "description": "文化类电子文献参考网站",
        "items": [
          {
            "title": "中国哲学书电子化计划",
            "url": "https://ctext.org/instructions/library/zh",
            "description": "一个线上古籍文献检索系统，是线上古典文献最丰富且最可靠的来源之一"
          },
          {
            "title": "CBETA Online",
            "url": "https://cbetaonline.cn/zh/",
            "description": "CBETA（中华电子佛典协会）是一个致力于汉文佛教经典数字化、整理与传播的非营利组织，现已成为全球最重要的汉文电子佛典资源平台之一。"
          }
        ]
      }
    ]
  },
  "changelog": {
    "entries": [
      {
        "date": "2026-07-03",
        "version": "v0.8.0",
        "title": "nav / footer 支持 hidden 字段 + 封面 fallback 彩色渐变",
        "type": "feature",
        "items": [
          {
            "text": "顶部导航 / 页脚链接加 `hidden: true` 字段,设为 true 时不渲染（不删行可恢复）"
          },
          {
            "text": "没配 cover 的文章卡片现在用每篇专属的彩色渐变兜底 (light/dark/sepia/cyberpunk 主题自适应)"
          },
          {
            "text": "site.author.name + site.author.url + site.social.github 改成 bijibaike.com 系列"
          },
          {
            "text": "页脚 copyright 同步成 '© 2026 笔记百科 / Bijibaike'"
          }
        ]
      },
      {
        "date": "2026-07-01",
        "version": "v0.7.0",
        "title": "配置驱动化：Home 描述读 config + index.html title 由 Vite 注入",
        "type": "improvement",
        "items": [
          {
            "text": "Home 首页的长描述从硬编码改成读 siteConfig.site.description"
          },
          {
            "text": "index.html 静态 title / lang / description 在 build 时由 Vite 插件从 vault/_config.md 注入"
          },
          {
            "text": "vault/_config.md 增加 site.social.email 字段（用于 Contact / Pricing 页面）"
          }
        ]
      },
      {
        "date": "2026-06-29",
        "version": "v0.6.0",
        "title": "Graph 加标签筛选 + 关系图按文件夹锁定 + 更新日志页",
        "description": "Graph 现在可以按标签筛选节点或锁定到某个 Pillar/Cluster,并新增 /changelog 时间线页面。",
        "type": "feature",
        "items": [
          {
            "text": "Graph 页面新加标签筛选 chip 行，点击只显示该标签的节点，再次点击清除"
          },
          {
            "text": "URL 加 ?scope= 参数支持按文件夹（单 Pillar / Cluster）锁定图谱"
          },
          {
            "text": "Pillar 与 Cluster 页面加上『看这个主题的关系图』入口"
          },
          {
            "text": "新增 /changelog 页面，按时间倒序显示每次更新（含版本号、类型、详细条目）"
          }
        ]
      },
      {
        "date": "2026-06-28",
        "version": "v0.5.0",
        "title": "14 种文章内容主题 + 移动端适配",
        "description": "文章页主题从 4 个扩到 14 个,移动端导航换成抽屉菜单。",
        "type": "feature",
        "items": [
          {
            "text": "导入 14 个 content-themes (default / academic / cyberpunk / receipt / sunset / aurora / bauhaus / knowledge / luxury / morandi / brutalism / github / terminal / magazine)"
          },
          {
            "text": "站点默认主题写在 _config.md，可被读者 localStorage 覆盖"
          },
          {
            "text": "移动端 hamburger 抽屉菜单"
          }
        ]
      },
      {
        "date": "2026-06-28",
        "version": "v0.4.0",
        "title": "中英双语 + 浏览器自动识别",
        "type": "feature",
        "items": [
          {
            "text": "所有 UI 字符串中英双语化，缺失的 en key 自动回退到中文"
          },
          {
            "text": "language detection 优先级：localStorage → navigator.language → _config.md 默认"
          }
        ]
      },
      {
        "date": "2026-06-27",
        "version": "v0.3.0",
        "title": "Pillar / Cluster 主题架构 + Git-aware 日期",
        "type": "feature",
        "items": [
          {
            "text": "Pillar / Cluster 两层模型，pillar.md 可写自定义描述/封面"
          },
          {
            "text": "文章 createdAt 优先取 frontmatter → 文件名 → git 首次提交 → 1970"
          }
        ]
      },
      {
        "date": "2026-06-26",
        "version": "v0.2.1",
        "title": "D3 力导向关系图重写",
        "type": "improvement",
        "items": [
          {
            "text": "forceLink + forceManyBody + forceCenter + forceCollide 四力联动"
          },
          {
            "text": "节点颜色按主标签 hash，大小按引用度平方根"
          }
        ]
      },
      {
        "date": "2026-06-25",
        "version": "v0.2.0",
        "title": "AdSense 合规接入 + Cookie consent",
        "type": "feature",
        "items": [
          {
            "text": "seo-kit/ads 模块：defineAds、generateAdsTxt、generateAutoAdsScript"
          },
          {
            "text": "Cookie 横幅默认关闭，Privacy 页面可重新打开"
          },
          {
            "text": "/about / /privacy / /contact 三页齐了"
          }
        ]
      }
    ]
  }
} as const;
