#!/usr/bin/env node
/**
 * build-config.mjs —— 把 vault/_config.md 编译成 src/config/site-config.ts
 *
 * - 读 vault/_config.md 的 frontmatter
 * - 类型校验（关键字段缺失时给出 warning 但不 fail build）
 * - 写 src/config/site-config.ts：纯 ESM TS，直接 `import { siteConfig } from ...`
 *
 * 跑法：
 *   - 在 npm run build 前自动调用
 *   - 也可独立跑 `npm run build:config`
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const CONFIG_MD = join(ROOT, 'vault', '_config.md');
const OUT_TS = join(ROOT, 'src', 'config', 'site-config.ts');
const OUT_JSON = join(ROOT, 'src', 'config', 'site-config.json');

if (!existsSync(CONFIG_MD)) {
  console.error(`✗ build-config: vault/_config.md not found at ${CONFIG_MD}`);
  console.error(`  请先跑 \`npm run vault:pull\` 把 vault 拉下来。`);
  process.exit(1);
}

const raw = readFileSync(CONFIG_MD, 'utf-8');
const { data, content } = matter(raw);

// ---- 类型校验 + 默认值补全 -----------------------------------------------

const site = data.site ?? {};
const seo = data.seo ?? {};
const ads = data.ads ?? {};
const vault = data.vault ?? {};
const nav = Array.isArray(data.nav) ? data.nav : [];
const footer = data.footer ?? {};
const pillars = Array.isArray(data.pillars) ? data.pillars : [];
const resources = data.resources ?? {};

const siteConfig = {
  site: {
    name: site.name ?? 'Obsidian Blog',
    shortName: site.shortName ?? site.name ?? 'Obsidian Blog',
    tagline: site.tagline ?? '',
    description: site.description ?? '',
    defaultTheme: site.defaultTheme ?? 'light',
    themes: Array.isArray(site.themes) && site.themes.length > 0
      ? site.themes
      : ['light', 'dark'],
    locale: site.locale ?? 'zh_CN',
    defaultLanguage: site.defaultLanguage ?? 'zh',
    languages: Array.isArray(site.languages) && site.languages.length > 0
      ? site.languages
      : ['zh', 'en'],
    author: {
      name: site.author?.name ?? '',
      url: site.author?.url ?? '',
    },
    social: {
      github: site.social?.github ?? '',
      twitter: site.social?.twitter ?? '',
      email: site.social?.email ?? '',
    },
  },
  seo: {
    siteUrl: seo.siteUrl ?? 'https://example.com',
    ogImage: seo.ogImage ?? '/og-image.svg',
    keywords: Array.isArray(seo.keywords) ? seo.keywords : [],
    twitter: seo.twitter ?? '',
  },
  ads: {
    enabled: !!ads.enabled,
    publisherId: ads.publisherId ?? '',
    verification: ads.verification !== false,
    autoAds: ads.autoAds !== false,
    consent: {
      required: ads.consent?.required !== false,
      categories: Array.isArray(ads.consent?.categories) ? ads.consent.categories : ['necessary', 'marketing'],
    },
  },
  vault: {
    repo: vault.repo ?? '',
    branch: vault.branch ?? 'main',
    ref: vault.ref ?? '',
    publicAttachmentsPath: vault.publicAttachmentsPath ?? '/attachments',
  },
  nav,
  footer: {
    copyright: footer.copyright ?? '',
    links: Array.isArray(footer.links) ? footer.links : [],
  },
  pillars,
  resources: {
    sections: Array.isArray(resources.sections) ? resources.sections : [],
  },
};

// 简短的字段警告
const warn = (msg) => console.warn(`⚠ build-config: ${msg}`);
if (!siteConfig.site.name) warn('site.name is missing');
if (!siteConfig.vault.repo) warn('vault.repo is missing (vault:pull will fall back to default)');
if (siteConfig.nav.length === 0) warn('nav is empty — header will have no links');

// ---- 写 src/config/site-config.ts -----------------------------------------

mkdirSync(dirname(OUT_TS), { recursive: true });

const ts = `// ⚠ AUTO-GENERATED by scripts/build-config.mjs
//   Source: vault/_config.md (frontmatter)
//   Do not edit this file directly — run \`npm run build:config\` after editing the vault config.

import type { SiteConfig } from './site-config.types';

export const siteConfig: SiteConfig = ${JSON.stringify(siteConfig, null, 2)} as const;
`;

writeFileSync(OUT_TS, ts, 'utf-8');
writeFileSync(OUT_JSON, JSON.stringify(siteConfig, null, 2), 'utf-8');

console.log(`✓ build-config: wrote ${OUT_TS.replace(ROOT + '/', '')} + ${OUT_JSON.replace(ROOT + '/', '')}`);
console.log(`  site.name=${siteConfig.site.name} | nav=${siteConfig.nav.length} | pillars=${siteConfig.pillars.length} | resources.sections=${siteConfig.resources.sections.length}`);
