/**
 * Vault configuration — Node-only (build-time).
 *
 * The vault itself is **git-ignored**; we fetch it at build time via
 * `scripts/setup-vault.mjs` (or `npm run vault:pull`).
 *
 * Single source of truth is `vault/_config.md` → `src/config/site-config.json`
 * (regenerated by `scripts/build-config.mjs`). We load it via dynamic
 * import at module load time so this file stays a regular TS module the
 * rest of the codebase can also import from, but only build scripts
 * actually call its exports.
 *
 *   private repos: prefix the URL with the token in CI, e.g.
 *     https://x-access-token:${GITHUB_TOKEN}@github.com/...
 *   but in development, use ssh keys or `gh auth setup-git`.
 */
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

interface VaultSubConfig {
  repo: string;
  branch: string;
  ref?: string;
  publicAttachmentsPath: string;
}

interface SiteConfigFile {
  vault: VaultSubConfig;
}

// Load site-config.json synchronously. `build-config` runs before any
// script that needs this, so the file is guaranteed to exist.
const cfgPath = path.resolve(root, 'src', 'config', 'site-config.json');
const raw = JSON.parse(readFileSync(cfgPath, 'utf-8')) as SiteConfigFile;
const v = raw.vault;

const repoSlug = v.repo.startsWith('http') || v.repo.startsWith('git@')
  ? v.repo
  : `https://github.com/${v.repo}.git`;

export const vaultConfig = {
  repo: repoSlug,
  branch: v.branch || 'main',
  ref: v.ref || undefined,

  /** Where to clone the vault locally. Default is `./vault` (project root). */
  localPath: path.resolve(root, 'vault'),

  /** Vault subdirectory containing attachments (images, PDFs, etc.). */
  attachmentsDir: 'attachments',

  /** Public URL prefix attachments get copied to. e.g. `attachments` → `/attachments/x.svg`. */
  publicAttachmentsPath: (v.publicAttachmentsPath || 'attachments').replace(/^\/+/, ''),
};

export type VaultConfig = typeof vaultConfig;
